### PR TITLE
Add filter step and improve testing

### PR DESCRIPTION
**Pull request by btjanaka**
## Description

Continuing the pipeline implementation, I have added the filter step. I have also added in some infrastructure for testing, including adding the Openeye license.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Implement and test filter step
- [x] Add Openeye license
- [x] Add more settings for testing and change command to simply be `pytest`

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by btjanaka** [comment]
Hi @jmaat, can you take a look at this PR? Thanks!

**Comment by jmaat** [comment]
@btjanaka This PR looks good for the most part. I am concerned about your work from from SMILES to OEMOL and if the oemols will include explicit hydrogens. Can you confirm that this isn't an issue by checking with prior code where we corrected this issue? I think this might be in a msg thread with Jeff Wagner.

**Review by jmaat — CHANGES_REQUESTED** [review]
@btjanaka This PR looks good for the most part. I am concerned about your work from from SMILES to OEMOL and if the oemols will include explicit hydrogens. Can you confirm that this isn't an issue by checking with prior code where we corrected this issue? I think this might be in a msg thread with Jeff Wagner.

**Comment by btjanaka** [comment]
Resolved offline. The filter step should not care about whether there are explicit hydrogens in the molecule.

**Pull request merged**
