### PR TITLE
Basic Pipeline Implementation

### PR DESCRIPTION
**Pull request by btjanaka**
## Description

Implementation and documentation of basic functionality of `DancePipeline`. Depends on #2 

## Todos

- [x] Implement `DancePipeline.__init__`
- [x] Test `DancePipeline.__init__`
- [x] Set up associated documentation

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by btjanaka** [comment]
Hi @jmaat, could you take a look at this PR? The most important code is in the last commit; it's where I actually start the class implementation and testing (it's very basic for now). Thanks!

**Comment by btjanaka** [comment]
Updated the commits since several of them were merged in #2

**Comment by jmaat** [comment]
@btjanaka What is `database_info : str`? Can you put an example of what you might use here?

**Review by jmaat — APPROVED** [review]
Approve when posted question is resolved

**Comment by btjanaka** [comment]
`DancePipeline` accepts several types of databases. `database_info` is just any information provided for each type. For example, if `database_type` is `SMILES`, then `database_info` would be the filename, such as `foo.smi`.

The table in the docstring shows the full info for each `database_type`. I also updated the table so that it shows the acceptable types for each `database_type`.

**Comment by btjanaka** [comment]
Just pushed some fixes that should make Travis work again

**Pull request merged**
